---
- name: "copy files"
  unarchive:
    src: backend/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "start server"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start